[package]
name = "working-title-main"
version = "0.1.0"
edition = "2021"

[dependencies]
working-title-core = { path = "../working-title-core" }
working-title-menu = { path = "../working-title-menu" }
working-title-player = { path = "../working-title-player" }

bevy = "0.12"
bevy_rapier3d = "0.23"
